### ISSUE TITLE
How to suppress this error?

### ISSUE THREAD

**Issue by TheTechRobo** [knarkzel/ogc-engine#3]
❯❯❯ rustup target add powerpc-unknown-eabi-1871534237463289148
error: toolchain 'stable-x86_64-unknown-linux-gnu' does not contain component 'rust-std' for target 'powerpc-unknown-eabi-1871534237463289148'
note: not all platforms have the standard library pre-compiled: https://doc.rust-lang.org/nightly/rustc/platform-support.html

**Comment by TheTechRobo** [comment]
same issue adding the json

**Comment by TheTechRobo** [comment]
Fixed using the command provided on the ogc-rs repo, although that really should be added to the readme (and justfile)

**Comment by lambdachad** [comment]
Are you trying to use `ogc-engine` for your own repository? If so, you need following:

- https://github.com/knarkzel/ogc-engine/blob/master/powerpc-unknown-eabi.json in `<project>/powerpc-unknown-eabi.json`.
- https://github.com/knarkzel/ogc-engine/blob/master/.cargo/config.toml in `<project>/.cargo/config.toml` to specify that you use the `.json` target provided above. Alternatively you can use `cargo +nightly build -Z build-std=core,alloc --target powerpc-unknown-eabi.json` instead, but using `config.toml` is easier because you can just run `cargo build`.
- When running the compiled binary, you need to add the `.elf` extension then open it in Dolphin. For audio to work inside Dolphin you need to enable `LLE`.

**Comment by TheTechRobo** [comment]
Thanks!
